import type { Metadata } from "next";
import { Righteous } from "next/font/google";
import Providers from "@/components/Providers";
import NavBar from "@/components/Navigation/NavBar";
import "./globals.css";

const righteous = Righteous({
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${righteous.className} antialiased`}>
                <Providers>
                    <NavBar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
